<a href="https://colab.research.google.com/github/ZehanQin/Card-D.-Krueger-A.-B.-1994-.-Minimum-Wages-and-Employment-Replication/blob/main/notebooks/02_Replication_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Import

In [1]:
raw_url = "https://raw.githubusercontent.com/ZehanQin/Card-D.-Krueger-A.-B.-1994-.-Minimum-Wages-and-Employment-Replication/refs/heads/main/data/raw/public.dat"

In [2]:
import pandas as pd

col_specs = [(0, 3),(4, 5),(6, 7),(8, 9),(10,11),(12,13),(14,15),(16,17),(18,19),(20,21),
             (25,30),(31,36),(37,42),(43,48),(83,88),(89,94),(95,100),(109,110),(121,126),(127,132),(133,138),(139,144),(173,178),(179,184),(185,190)]
col_names = ['SHEET', 'CHAIN', 'CO_OWNED', 'STATE','SOUTNJ','CENTRALJ','NORTHJ','PA1','PA2','SHORE',
             'EMPFT','EMPPT','NMGRS','WAGE_ST','PSODA','PFRY','PENTREE','STATUS2','EMPFT2','EMPPT2','NMGRS2','WAGE_ST2','PSODA2','PFRY2','PENTREE2']

df_raw = pd.read_fwf(raw_url, colspecs=col_specs, names=col_names)
df_raw.head()

,SHEET,CHAIN,CO_OWNED,STATE,SOUTNJ,CENTRALJ,NORTHJ,PA1,PA2,SHORE,...,PFRY,PENTREE,STATUS2,EMPFT2,EMPPT2,NMGRS2,WAGE_ST2,PSODA2,PFRY2,PENTREE2
0,46,1,0,0,0,0,0,1,0,0,...,1.03,0.52,1,3.50,35.00,3.00,4.30,1.03,.,0.94
1,49,2,0,0,0,0,0,1,0,0,...,0.90,2.35,1,0.00,15.00,4.00,4.45,1.01,0.89,2.35
2,506,2,1,0,0,0,0,1,0,0,...,0.74,2.33,1,3.00,7.00,4.00,5.00,0.95,0.74,2.33
3,56,4,1,0,0,0,0,1,0,0,...,0.82,1.79,1,0.00,36.00,2.00,5.25,0.92,0.79,0.87
4,61,4,1,0,0,0,0,1,0,0,...,0.77,1.65,1,28.00,3.00,6.00,4.75,1.01,0.84,0.95

In [3]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SHEET     410 non-null    int64
 1   CHAIN     410 non-null    int64
 2   CO_OWNED  410 non-null    int64
 3   STATE     410 non-null    int64
 4   SOUTNJ    410 non-null    int64
 5   CENTRALJ  410 non-null    int64
 6   NORTHJ    410 non-null    int64
 7   PA1       410 non-null    int64
 8   PA2       410 non-null    int64
 9   SHORE     410 non-null    int64
 10  EMPFT     410 non-null    object
 11  EMPPT     410 non-null    object
 12  NMGRS     410 non-null    object
 13  WAGE_ST   410 non-null    object
 14  PSODA     410 non-null    object
 15  PFRY      410 non-null    object
 16  PENTREE   410 non-null    object
 17  STATUS2   410 non-null    int64
 18  EMPFT2    410 non-null    object
 19  EMPPT2    410 non-null    object
 20  NMGRS2    410 non-null    object
 21  WAGE_ST2  410 non-null    object
 22  PSODA2    410 non-null    object
 23  PFRY2     410 non-null    object
 24  PENTREE2  410 non-null    object
dtypes: int64(11), object(14)
memory usage: 80.2+ KB

# Phase 2

In [4]:
import numpy as np
import pandas as pd

In [5]:
df_raw.isna()

,SHEET,CHAIN,CO_OWNED,STATE,SOUTNJ,CENTRALJ,NORTHJ,PA1,PA2,SHORE,...,PFRY,PENTREE,STATUS2,EMPFT2,EMPPT2,NMGRS2,WAGE_ST2,PSODA2,PFRY2,PENTREE2
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
406,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
407,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
408,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
409,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
obj_columns = ["EMPFT","EMPPT","NMGRS","WAGE_ST","PSODA","PFRY","PENTREE","EMPFT2","EMPPT2","NMGRS2","WAGE_ST2","PSODA2","PFRY2","PENTREE2"]

df_raw[obj_columns] = df_raw[obj_columns].replace({".":np.nan})

for character in obj_columns:
  df_raw[character] = pd.to_numeric(df_raw[character], errors="coerce")

In [7]:
df_raw[obj_columns].dtypes

EMPFT       float64
EMPPT       float64
NMGRS       float64
WAGE_ST     float64
PSODA       float64
PFRY        float64
PENTREE     float64
EMPFT2      float64
EMPPT2      float64
NMGRS2      float64
WAGE_ST2    float64
PSODA2      float64
PFRY2       float64
PENTREE2    float64
dtype: object

In [8]:
df_raw[obj_columns].isna()

,EMPFT,EMPPT,NMGRS,WAGE_ST,PSODA,PFRY,PENTREE,EMPFT2,EMPPT2,NMGRS2,WAGE_ST2,PSODA2,PFRY2,PENTREE2
0,False,False,False,True,False,False,False,False,False,False,False,False,True,False
1,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,False,False,False,False,False,False,False,False,False,False,False,False,False,False
406,False,False,False,False,False,False,False,False,False,False,False,False,False,False
407,False,False,False,False,False,False,False,False,False,False,False,False,False,False
408,False,False,False,False,False,False,False,False,False,False,False,False,False,False
409,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df_raw[obj_columns].isna().sum()

EMPFT        6
EMPPT        4
NMGRS        6
WAGE_ST     20
PSODA        8
PFRY        17
PENTREE     12
EMPFT2      12
EMPPT2      10
NMGRS2       6
WAGE_ST2    21
PSODA2      22
PFRY2       28
PENTREE2    24
dtype: int64

In [10]:
df_raw["STATUS2"].value_counts()

STATUS2
1    399
3      6
2      2
4      1
0      1
5      1
Name: count, dtype: int64

In [11]:
permanent_close = (df_raw["STATUS2"] == 3)
temporary_close = df_raw["STATUS2"].isin([2, 4, 5])
reject_2nd_interview = (df_raw["STATUS2"] == 0)

df_raw.loc[permanent_close, ["EMPFT2", "EMPPT2","NMGRS2"]] = 0
df_raw.loc[temporary_close | reject_2nd_interview, ['EMPFT2', 'EMPPT2','NMGRS2']] = np.nan

In [12]:
df_raw.groupby("STATUS2")[["EMPFT2", "EMPPT2"]].mean()

           EMPFT2     EMPPT2
STATUS2
0             NaN        NaN
1        8.401786  18.961929
2             NaN        NaN
3        0.000000   0.000000
4             NaN        NaN
5             NaN        NaN

In [13]:
df_raw["Full_Time_Equivalent1"] = (df_raw["EMPFT"]+df_raw["NMGRS"]) + 0.5*df_raw["EMPPT"]
df_raw["Full_Time_Equivalent2"] = (df_raw["EMPFT2"]+df_raw["NMGRS2"]) + 0.5*df_raw["EMPPT2"]

In [14]:
df_raw["Full_Time_Equivalent1"]

0      40.50
1      13.75
2       8.50
3      34.00
4      24.00
       ...
405     9.00
406     9.75
407    24.50
408    14.00
409    19.50
Name: Full_Time_Equivalent1, Length: 410, dtype: float64

In [15]:
df_raw["Full_Time_Equivalent2"]

0      24.00
1      11.50
2      10.50
3      20.00
4      35.50
       ...
405    23.75
406    17.50
407    20.50
408    20.50
409    25.00
Name: Full_Time_Equivalent2, Length: 410, dtype: float64

In [16]:
df_raw[["Full_Time_Equivalent1","Full_Time_Equivalent2"]].describe()

       Full_Time_Equivalent1  Full_Time_Equivalent2
count             398.000000             396.000000
mean               20.998869              21.054293
std                 9.749805               9.094453
min                 5.000000               0.000000
25%                14.562500              14.500000
50%                19.500000              20.500000
75%                24.500000              26.500000
max                85.000000              60.500000

In [17]:
df_raw.groupby("STATUS2")[["Full_Time_Equivalent2"]].mean()

         Full_Time_Equivalent2
STATUS2
0                          NaN
1                    21.378205
2                          NaN
3                     0.000000
4                          NaN
5                          NaN

In [18]:
tab_mean = df_raw.groupby("STATE")[["Full_Time_Equivalent1","Full_Time_Equivalent2"]].mean()
tab_std = df_raw.groupby("STATE")[["Full_Time_Equivalent1", "Full_Time_Equivalent2"]].std()
tab_amount = df_raw.groupby("STATE")[["Full_Time_Equivalent1", "Full_Time_Equivalent2"]].count()

In [19]:
tab = pd.concat({"mean": tab_mean, "std": tab_std, "count": tab_amount}, axis=1)

In [20]:
tab

                       mean                                         std  \
      Full_Time_Equivalent1 Full_Time_Equivalent2 Full_Time_Equivalent1
STATE
0                 23.331169             21.165584             11.856283
1                 20.439408             21.027429              9.106239

                                            count
      Full_Time_Equivalent2 Full_Time_Equivalent1 Full_Time_Equivalent2
STATE
0                  8.276732                    77                    77
1                  9.293024                   321                   319

In [21]:
wage_tab_mean = df_raw.groupby("STATE")[["WAGE_ST","WAGE_ST2"]].mean()
wage_tab_std = df_raw.groupby("STATE")[["WAGE_ST","WAGE_ST2"]].std()
wage_tab_amount = df_raw.groupby("STATE")[["WAGE_ST","WAGE_ST2"]].count()

In [22]:
wage_tab = pd.concat({"mean": wage_tab_mean, "std": wage_tab_std, "count": wage_tab_amount}, axis=1)
wage_tab

           mean                 std             count
        WAGE_ST  WAGE_ST2   WAGE_ST  WAGE_ST2 WAGE_ST WAGE_ST2
STATE
0      4.630132  4.617465  0.351687  0.357478      76       71
1      4.612134  5.080849  0.346351  0.104545     314      318

In [23]:
df_raw["FULLMEAL"] = df_raw["PSODA"] + df_raw["PFRY"] + df_raw["PENTREE"]
df_raw["FULLMEAL2"] = df_raw["PSODA2"] + df_raw["PFRY2"] + df_raw["PENTREE2"]

In [24]:
price_tab_mean = df_raw.groupby("STATE")[["FULLMEAL","FULLMEAL2"]].mean()
price_tab_std = df_raw.groupby("STATE")[["FULLMEAL","FULLMEAL2"]].std()
price_tab_amount = df_raw.groupby("STATE")[["FULLMEAL","FULLMEAL2"]].count()

In [25]:
price_tab = pd.concat({"mean": price_tab_mean, "std": price_tab_std, "count": price_tab_amount}, axis=1)
price_tab

           mean                 std              count
       FULLMEAL FULLMEAL2  FULLMEAL FULLMEAL2 FULLMEAL FULLMEAL2
STATE
0      3.042368  3.026620  0.601090  0.566291       76        71
1      3.351061  3.414754  0.644463  0.635643      311       305

In [26]:
before_policy_nj = tab_mean.loc[1, "Full_Time_Equivalent1"]
after_policy_nj = tab_mean.loc[1, "Full_Time_Equivalent2"]
before_policy_pa = tab_mean.loc[0, "Full_Time_Equivalent1"]
after_policy_pa = tab_mean.loc[0, "Full_Time_Equivalent2"]

change_in_nj = after_policy_nj - before_policy_nj
change_in_pa = after_policy_pa - before_policy_pa

change_in_nj, change_in_pa

(np.float64(0.5880213673961663), np.float64(-2.1655844155844157))

In [27]:
DiD = change_in_nj - change_in_pa
DiD

np.float64(2.753605782980582)

In [28]:
df_raw["treat"] = df_raw["STATE"]
df_raw["store_id"] = df_raw["SHEET"]

In [29]:
df_long = df_raw.melt(id_vars = ["store_id", "treat"], value_vars = ["Full_Time_Equivalent1", "Full_Time_Equivalent2"], var_name = "category", value_name="FTE_value")

In [30]:
df_long

     store_id  treat               category  FTE_value
0          46      0  Full_Time_Equivalent1      40.50
1          49      0  Full_Time_Equivalent1      13.75
2         506      0  Full_Time_Equivalent1       8.50
3          56      0  Full_Time_Equivalent1      34.00
4          61      0  Full_Time_Equivalent1      24.00
..        ...    ...                    ...        ...
815       423      1  Full_Time_Equivalent2      23.75
816       424      1  Full_Time_Equivalent2      17.50
817       426      1  Full_Time_Equivalent2      20.50
818       427      1  Full_Time_Equivalent2      20.50
819       428      1  Full_Time_Equivalent2      25.00

[820 rows x 4 columns]

In [31]:
df_long["post_change"] = (df_long["category"] == "Full_Time_Equivalent2").astype(int)

df_long

     store_id  treat               category  FTE_value  post_change
0          46      0  Full_Time_Equivalent1      40.50            0
1          49      0  Full_Time_Equivalent1      13.75            0
2         506      0  Full_Time_Equivalent1       8.50            0
3          56      0  Full_Time_Equivalent1      34.00            0
4          61      0  Full_Time_Equivalent1      24.00            0
..        ...    ...                    ...        ...          ...
815       423      1  Full_Time_Equivalent2      23.75            1
816       424      1  Full_Time_Equivalent2      17.50            1
817       426      1  Full_Time_Equivalent2      20.50            1
818       427      1  Full_Time_Equivalent2      20.50            1
819       428      1  Full_Time_Equivalent2      25.00            1

[820 rows x 5 columns]

In [32]:
import statsmodels.formula.api as sm

df_reg = df_long[["FTE_value", "treat", "post_change", "store_id"]].dropna().copy()

model = sm.ols("FTE_value ~ treat + post_change + treat:post_change", data=df_reg)
results = model.fit(cov_type="cluster", cov_kwds={"groups": df_reg["store_id"]})

results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              FTE_value   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.806
Date:                Tue, 10 Mar 2026   Prob (F-statistic):              0.146
Time:                        15:12:31   Log-Likelihood:                -2904.2
No. Observations:                 794   AIC:                             5816.
Df Residuals:                     790   BIC:                             5835.
Df Model:                           3
Covariance Type:              cluster
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            23.3312      1.347     17.327      0.000      20.692      25.970
treat                -2.8918      1.437     -2.013      0.044      -5.707      -0.076
post_change          -2.1656      1.218     -1.778      0.075      -4.553       0.222
treat:post_change     2.7536      1.306      2.108      0.035       0.193       5.314
==============================================================================
Omnibus:                      218.742   Durbin-Watson:                   1.840
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              804.488
Skew:                           1.268   Prob(JB):                    2.03e-175
Kurtosis:                       7.229   Cond. No.                         11.3
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
"""

In [33]:
Table_Summary = pd.concat([tab, wage_tab, price_tab])
Table_Summary

                       mean                                         std  \
      Full_Time_Equivalent1 Full_Time_Equivalent2 Full_Time_Equivalent1
STATE
0                 23.331169             21.165584             11.856283
1                 20.439408             21.027429              9.106239
0                       NaN                   NaN                   NaN
1                       NaN                   NaN                   NaN
0                       NaN                   NaN                   NaN
1                       NaN                   NaN                   NaN

                                            count                        \
      Full_Time_Equivalent2 Full_Time_Equivalent1 Full_Time_Equivalent2
STATE
0                  8.276732                  77.0                  77.0
1                  9.293024                 321.0                 319.0
0                       NaN                   NaN                   NaN
1                       NaN                   NaN                   NaN
0                       NaN                   NaN                   NaN
1                       NaN                   NaN                   NaN

           mean                 std             count               mean  \
        WAGE_ST  WAGE_ST2   WAGE_ST  WAGE_ST2 WAGE_ST WAGE_ST2  FULLMEAL
STATE
0           NaN       NaN       NaN       NaN     NaN      NaN       NaN
1           NaN       NaN       NaN       NaN     NaN      NaN       NaN
0      4.630132  4.617465  0.351687  0.357478    76.0     71.0       NaN
1      4.612134  5.080849  0.346351  0.104545   314.0    318.0       NaN
0           NaN       NaN       NaN       NaN     NaN      NaN  3.042368
1           NaN       NaN       NaN       NaN     NaN      NaN  3.351061

                      std              count
      FULLMEAL2  FULLMEAL FULLMEAL2 FULLMEAL FULLMEAL2
STATE
0           NaN       NaN       NaN      NaN       NaN
1           NaN       NaN       NaN      NaN       NaN
0           NaN       NaN       NaN      NaN       NaN
1           NaN       NaN       NaN      NaN       NaN
0      3.026620  0.601090  0.566291     76.0      71.0
1      3.414754  0.644463  0.635643    311.0     305.0